version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:20-alpine
    steps:
      - checkout
      - run:
          name: install npm dependencies
          command: |
            npm install
  build_docker_image:
    docker:
      - image: circleci/node:20-alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker build -t nodejsApp1 -t moustafaashraf/nodejsApp1:latest .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push moustafaashraf/nodejsApp1:latest
workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
