# POST http://localhost:8080/api/patient/signup HTTP/1.1
# content-type: application/json

# {
#     "FirstName":"testuser",
#     "LastName":"user2",
#     "Email":"email28",
#     "Password":"123",
#     "patientphonenumber":[
#         {"PhoneNumber":1},
#         {"PhoneNumber":2},
#         {"PhoneNumber":3},
#         {"PhoneNumber":4}
#     ]
# }

# {
#     "FirstName":"api",
#     "LastName":"apiUser",
#     "Email":"email27",
#     "Password":"123",
#     "patientphonenumber":[
#         {"PhoneNumber":1},
#         {"PhoneNumber":2},
#         {"PhoneNumber":3},
#         {"PhoneNumber":4}
#     ]
# }


POST http://localhost:8080/api/patient/timeslot/1 HTTP/1.1
content-type: application/json
authorization: "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlhdCI6MTcxOTMzMTIzNywiZXhwIjoxNzUwODY3MjM3fQ.V3Hw57kqtl9dOEsFMXXrnzuSlUYJ8ChiEO9cgQprhAw"

{
   "patient_id":30
}